/** Mirrors KhushBackend analyticsEvent.catalog.js */
export const ANALYTICS_EVENTS = Object.freeze({
  SESSION_START: "session_start",
  SESSION_END: "session_end",
  PAGE_VIEW: "page_view",
  ROUTE_CHANGE: "route_change",
  SEARCH: "search",
  SEARCH_CLICK: "search_click",
  SEARCH_NO_RESULTS: "search_no_results",
  SEARCH_FILTER_APPLIED: "search_filter_applied",
  SEARCH_SORT_CHANGED: "search_sort_changed",
  CATEGORY_VIEW: "category_view",
  SUBCATEGORY_VIEW: "subcategory_view",
  SECTION_VIEW: "section_view",
  PRODUCT_VIEW: "product_view",
  PRODUCT_IMAGE_SWIPE: "product_image_swipe",
  SIZE_SELECT: "size_select",
  COLOR_SELECT: "color_select",
  ADD_TO_CART: "add_to_cart",
  REMOVE_FROM_CART: "remove_from_cart",
  CART_VIEW: "cart_view",
  CART_QTY_INCREASE: "cart_quantity_increase",
  CART_QTY_DECREASE: "cart_quantity_decrease",
  CHECKOUT_STARTED: "checkout_started",
  BEGIN_CHECKOUT: "begin_checkout",
  CHECKOUT_ADDRESS_SELECTED: "checkout_address_selected",
  CHECKOUT_ADDRESS_ADDED: "checkout_address_added",
  CHECKOUT_DELIVERY_SELECTED: "checkout_delivery_option_selected",
  PAYMENT_MODE_SELECTED: "payment_mode_selected",
  PAYMENT_INITIATED: "payment_initiated",
  PAYMENT_SUCCESS: "payment_success",
  PAYMENT_FAILED: "payment_failed",
  ORDER_PLACED: "order_placed",
  ORDER_CONFIRMED: "order_confirmed",
  ORDER_TRACKING_VIEW: "order_tracking_view",
  ORDER_CANCELLED: "order_cancelled",
  REFUND_REQUESTED: "refund_requested",
  WISHLIST_ADD: "wishlist_add",
  WISHLIST_REMOVE: "wishlist_remove",
  SHARE_CLICK: "share_click",
  COUPON_APPLY_ATTEMPT: "coupon_apply_attempt",
  COUPON_APPLIED: "coupon_applied",
  COUPON_REMOVED: "coupon_removed",
  AUTH_LOGIN_STARTED: "auth_login_started",
  AUTH_LOGIN_SUCCESS: "auth_login_success",
  AUTH_LOGIN_FAILED: "auth_login_failed",
  AUTH_SIGNUP_STARTED: "auth_signup_started",
  AUTH_SIGNUP_SUCCESS: "auth_signup_success",
  AUTH_LOGOUT: "auth_logout",
  PROFILE_UPDATED: "profile_updated",
  ADDRESS_ADDED: "address_added",
  ADDRESS_UPDATED: "address_updated",
  NOTIFICATION_OPENED: "notification_opened",
  RECOMMENDATION_CLICK: "recommendation_click",
  API_ERROR: "api_error",
  API_TIMEOUT: "api_timeout",
  NETWORK_ERROR: "network_error",
  UI_EXCEPTION: "ui_exception",
});

export const EVENTS_REQUIRING_USER_ID = Object.freeze([
  ANALYTICS_EVENTS.ADD_TO_CART,
  ANALYTICS_EVENTS.CHECKOUT_STARTED,
]);
